### ISSUE TITLE
Some questions about SimDeblur?

### ISSUE THREAD

**Issue by jianghongsun** [ljzycmd/SimDeblur#2]
hi,Thank you for you sharing！Can you share your deblurring model. Can your model run on cpu.

**Comment by ljzycmd** [comment]
It is hard to train a model on the cpu, but you can modify the Trainer class to support cpu testing easily. Later I will also add the code for testing on the cpu.

**Comment by JoshonSmith** [comment]
can you provide some pretrained deblurring models?
