### ISSUE TITLE
Can you provide the training details of DBN? 

### ISSUE THREAD

**Issue by TaoWangzj** [ljzycmd/SimDeblur#6]
Thank you for your great job. I try to retrain the DBN by your provided dbn_dvd.yaml, and i meet the following problem in the training stage:
![image](https://user-images.githubusercontent.com/66311882/133191387-af14244d-9013-4a7b-9ddf-6259f3c553a2.png)

**Comment by ljzycmd** [comment]
I adopt the default configurations in dbn_dvd.yaml to train it, and it seems that everything is OK.
![image](https://user-images.githubusercontent.com/15065356/133192643-50dc9453-9662-4785-adb6-4efb5900219d.png)
I will email the training logs to you. Please check your Gmail.

**Comment by TaoWangzj** [comment]
Thank you very much!!
